### ISSUE TITLE
compute_returns

### ISSUE THREAD

**Issue by hudso** [contravariant/testR#3]
I think having `compute_returns` default to calculating annualized returns could lead to some misuse in the future. When someone hears the name `compute_returns` it could mean a lot of different things to her. Maybe it should be `compute_returns_annualized` or `compute_cum_ret_annld`?

**Comment by contravariant** [comment]
Agreed. I will have a `compute_returns(period)` or something in place of "period" (do you prefer "horizon"?) and then have a few specialized functions, maybe `compute_returns_annualized` and `compute_returns_monthly`.

**Comment by hudso** [comment]
“horizon” is probably less technical but more evocative of the essence of the function. But, it’s not that big of a deal either way.

Josh
+1 (212) 257-4290

**Comment by contravariant** [comment]
Josh, I already have two functions called `compute_returns_yearly` and `compute_returns_monthly`. They return a vector. For example the yearly function returns the annual returns for each year.

So what I did was to extend `compute_returns`. There is an extra `horizon` argument, which defaults to 252. If one wants to change, it's easy to do by specializing the function.

**Comment by hudso** [comment]
Perfect.
