### ISSUE TITLE
Momentum calculation

### ISSUE THREAD

**Issue by hudso** [contravariant/testR#5]
@contravariant Would you please explain why you calculate momentum this way:
```
MOME_est <- R[-1:-width, ]/R[1:(ndates - width)]
```
It appears as if every stock's cumulative return (since the first date in the matrix) is being divided by the first stock in the matrix's cumulative return on that same day.

```
Browse[2]> str(R[-1:-width, ])
 num [1:5236, 1:11937] -0.206 -0.189 -0.194 -0.125 -0.152 ...
 - attr(*, "dimnames")=List of 2
  ..$ date: chr [1:5236] "1994-10-28" "1994-10-31" "1994-11-01" "1994-11-02" ...
  ..$ id  : chr [1:11937] "000360206" "000361105" "000752105" "00077R108" ...
Browse[2]> str(R[1:(ndates - width)])
 num [1:5236] 0.0163 0.0174 0.0266 0.013 -0.0447 ...
Browse[2]> str(R[, 1])
 Named num [1:5362] 0.0163 0.0174 0.0266 0.013 -0.0447 ...
 - attr(*, "names")= chr [1:5362] "1994-05-02" "1994-05-03" "1994-05-04" "1994-05-05" ...
```

There are a few things that confuse me. Why is every stock apparently being compared to the first stock? Why calculate momentum as a ratio versus a simple cumulative return from the start of the window to the end of the window?

**Comment by contravariant** [comment]
Risght. I made two mistakes there. First, that first formula you pasted is wrong. It should be 

MOME_est <- R[-1:-width, ] / R[1:(ndates - width), ]

It did not error out. And I also changed this in a previous line.

 R %<>% {.[is.na(.)] <- 0; .} %>% {. + 1} %>% 
    apply(2, cumprod) 

Now the calculation is correct: it's the MOME_est[d, id] = (cumulative return for id up to date d)/(cumulative return for id up to date d-width) = cumulative return from (d-width) to d.
